# Generated by Django 3.2 on 2023-06-20 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('EQ', 'Emotional Quotient'), ('IQ', 'Intelligence Quotient')], default='IQ', max_length=2)),
                ('secret_key', models.CharField(default='GRFsN_a9OA', max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('max_points', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.CharField(max_length=128)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_poll', to='Tests.poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=128)),
                ('selection', models.BooleanField(default=False)),
                ('weight_selection_two', models.FloatField(default=1)),
                ('answer_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_poll', to='Tests.poll')),
                ('answer_question_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='Tests.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
