# Generated by Django 3.2 on 2023-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='weight_selection_two',
            new_name='weight_selection',
        ),
        migrations.AlterField(
            model_name='poll',
            name='secret_key',
            field=models.CharField(default='m3pgDYlf3Q', max_length=10, unique=True),
        ),
    ]
