# Generated by Django 3.2 on 2023-06-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0002_auto_20230620_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='poll',
            new_name='question_poll',
        ),
        migrations.AlterField(
            model_name='poll',
            name='secret_key',
            field=models.CharField(default='6rE4M8kjJQ', max_length=10, unique=True),
        ),
    ]
