# Generated by Django 3.2 on 2023-06-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0004_auto_20230624_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selection',
        ),
        migrations.AddField(
            model_name='poll',
            name='answers',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='poll',
            name='passage_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='secret_key',
            field=models.CharField(default='yPi1FrDApw', max_length=10, unique=True),
        ),
    ]
