# Generated by Django 3.2 on 2023-06-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0005_auto_20230624_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='passage_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='secret_key',
            field=models.CharField(default='R6ncfpRing', max_length=10, unique=True),
        ),
    ]
