# Generated by Django 3.2 on 2023-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tests', '0006_auto_20230625_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='max_points',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='secret_key',
            field=models.CharField(default='O7NUTD2lIA', max_length=10, unique=True),
        ),
    ]
